steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west9-docker.pkg.dev/$PROJECT_ID/studious-linker-447715-t9/ml_ops_train',
    '-f',
    './dockerfiles/train.dockerfile'
  ]
  env: 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west9-docker.pkg.dev/$PROJECT_ID/studious-linker-447715-t9/ml_ops_train'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
