output_dir: "./results"
evaluation_strategy: "epoch"
learning_rate: 0.0001
epochs: 100
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
weight_decay: 0.01
save_total_limit: 3
num_train_epochs: 3
predict_with_generate: true
logging_dir: "./logs"
logging_steps: 10
save_steps: 500
