name: Code formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install ruff black mypy

      - name: Lint and fix with Ruff
        run: ruff check . --fix

      - name: Format with Black
        run: black .

      - name: Static type checking with MyPy
        run: mypy .